version: '2.19'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: nizygg/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    env_file: .env
    image: nizygg/taski_frontend
    command: cp -r /app/build/. /frontend_static
    volumes:
      - static:/frontend_static
  gateway:
    image: nizygg/taski_gateway
    volumes:
      - static:/staticfiles
    ports: 
      - 8000:80
